# Generated by Django 5.2.6 on 2025-10-04 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receipt_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Foreign key to receipt_service.Receipt",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_index=True, help_text="Foreign key to auth_service.User"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR Processing"),
                            ("categorization", "AI Categorization"),
                            ("data_extraction", "Data Extraction"),
                            ("completed", "Completed"),
                        ],
                        default="ocr",
                        max_length=30,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Processing progress 0-100"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher values = higher priority"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_stage", models.CharField(blank=True, max_length=30)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                (
                    "processing_config",
                    models.JSONField(
                        default=dict, help_text="OCR and AI processing configuration"
                    ),
                ),
            ],
            options={
                "db_table": "ai_processing_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["receipt_id"], name="ai_processi_receipt_39f22d_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="ai_processi_user_id_62360a_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_processi_status_aa4b18_idx",
                    ),
                    models.Index(
                        fields=["current_stage", "priority"],
                        name="ai_processi_current_5bf891_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(help_text="Full OCR extracted text"),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Overall OCR confidence 0.0-1.0"),
                ),
                (
                    "language_detected",
                    models.CharField(
                        default="en", help_text="Detected language code", max_length=10
                    ),
                ),
                (
                    "ocr_engine",
                    models.CharField(
                        default="google_vision",
                        help_text="OCR engine used",
                        max_length=50,
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(help_text="Time taken for OCR processing"),
                ),
                (
                    "image_preprocessing_applied",
                    models.JSONField(
                        default=list, help_text="List of preprocessing steps applied"
                    ),
                ),
                (
                    "text_regions",
                    models.JSONField(
                        default=list,
                        help_text="Text regions with bounding boxes and confidence",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_result",
                        to="ai_service.processingjob",
                    ),
                ),
            ],
            options={
                "db_table": "ai_ocr_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Extracted vendor/merchant name",
                        max_length=255,
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(
                        blank=True, help_text="Extracted receipt date", null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Extracted total amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Extracted currency code", max_length=3
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tip_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "line_items",
                    models.JSONField(
                        default=list, help_text="Extracted line items with prices"
                    ),
                ),
                (
                    "vendor_address",
                    models.TextField(blank=True, help_text="Extracted vendor address"),
                ),
                (
                    "vendor_phone",
                    models.CharField(
                        blank=True, help_text="Extracted vendor phone", max_length=50
                    ),
                ),
                (
                    "confidence_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Confidence scores for each extracted field",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        default="gemini_parsing",
                        help_text="Extraction method used",
                        max_length=50,
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(help_text="Time taken for data extraction"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_data",
                        to="ai_service.processingjob",
                    ),
                ),
            ],
            options={
                "db_table": "ai_extracted_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategoryPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "predicted_category_id",
                    models.UUIDField(
                        help_text="Predicted category ID from receipt_service"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Prediction confidence 0.0-1.0"),
                ),
                (
                    "reasoning",
                    models.TextField(help_text="AI reasoning for the prediction"),
                ),
                (
                    "alternative_predictions",
                    models.JSONField(
                        default=list,
                        help_text="List of alternative category predictions with confidence scores",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="gemini-1.5-flash",
                        help_text="AI model used",
                        max_length=50,
                    ),
                ),
                (
                    "input_features",
                    models.JSONField(
                        default=dict, help_text="Features used for prediction"
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(help_text="Time taken for categorization"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_prediction",
                        to="ai_service.processingjob",
                    ),
                ),
            ],
            options={
                "db_table": "ai_category_predictions",
                "ordering": ["-created_at"],
            },
        ),
    ]
