# Generated by Django 5.2.6 on 2025-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryprediction",
            name="model_version",
            field=models.CharField(
                default="gemini-2.5-flash", help_text="AI model used", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="currency",
            field=models.CharField(
                default="INR", help_text="Currency code (ISO 4217)", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="line_items",
            field=models.JSONField(
                blank=True, default=list, help_text="Extracted line items"
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="subtotal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Extracted subtotal",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="tax_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Extracted tax amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Extracted total amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="vendor_name",
            field=models.CharField(
                blank=True,
                default="Unknown",
                help_text="Extracted vendor/merchant name",
                max_length=255,
                null=True,
            ),
        ),
    ]
