# Generated by Django 5.2.6 on 2025-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0002_alter_categoryprediction_model_version_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="processingjob",
            name="ai_processi_current_5bf891_idx",
        ),
        migrations.RemoveField(
            model_name="categoryprediction",
            name="input_features",
        ),
        migrations.RemoveField(
            model_name="extracteddata",
            name="tip_amount",
        ),
        migrations.RemoveField(
            model_name="extracteddata",
            name="vendor_address",
        ),
        migrations.RemoveField(
            model_name="extracteddata",
            name="vendor_phone",
        ),
        migrations.RemoveField(
            model_name="ocrresult",
            name="image_preprocessing_applied",
        ),
        migrations.RemoveField(
            model_name="ocrresult",
            name="text_regions",
        ),
        migrations.RemoveField(
            model_name="processingjob",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="processingjob",
            name="processing_config",
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["current_stage"], name="ai_processi_current_18e9fc_idx"
            ),
        ),
    ]
