# Generated by Django 5.2.6 on 2025-10-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_service",
            "0003_remove_processingjob_ai_processi_current_5bf891_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="extracteddata",
            name="currency",
            field=models.CharField(
                blank=True,
                default="INR",
                help_text="Currency code (ISO 4217)",
                max_length=3,
                null=True,
            ),
        ),
    ]
