"""
Django settings for receiptmanager project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab
from dotenv import load_dotenv
load_dotenv()  # Load environment variables from a .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "unsafe-default")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] 
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
}

# Custom User Model
AUTH_USER_MODEL = 'auth_service.User'  # Important: Set custom user model

# Pagination Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # For admin
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Add this to handle CSRF
    # 'DEFAULT_RENDERER_CLASSES': [
    #     'rest_framework.renderers.JSONRenderer',
    # ],
    # 'DEFAULT_PARSER_CLASSES': [
    #     'rest_framework.parsers.JSONParser',
    #     'rest_framework.parsers.FormParser',
    #     'rest_framework.parsers.MultiPartParser',
    # ],
    'DEFAULT_PAGINATION_CLASS': 'shared.utils.pagination.OptimizedPageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'shared.utils.exceptions.exception_handler',
}

# Redis connection info
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))
REDIS_DB_CACHE = os.environ.get('REDIS_DB_CACHE', 1)  # Cache for pagination
REDIS_DB_BROKER = os.environ.get('REDIS_DB_BROKER', 0)  # Broker for Celery

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_BROKER}"  # Redis message broker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Store Celery task results
CELERY_RESULT_BACKEND = 'django-db'

CELERY_TASK_ACKS_LATE = True  # Ensure tasks are not lost if worker crashes
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_SOFT_TIME_LIMIT = 3600  # Tasks can't run more than 1 hour
CELERY_TASK_TIME_LIMIT = 7200       # Hard limit for tasks

# Optional: set a default timeout for cache entries
CACHE_TTL = 300  # seconds (5 minutes)

# Cache Settings for Pagination
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
        },
        'KEY_PREFIX': 'receipt_app',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Celery Beat Schedule for cleanup tasks
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-magic-links': {
        'task': 'apps.auth_service.tasks.cleanup_expired_magic_links',
        'schedule': crontab(minute=0, hour=2),  # Daily at 2 AM
    },
    'cleanup-expired-email-verifications': {
        'task': 'apps.auth_service.tasks.cleanup_expired_email_verifications',
        'schedule': crontab(minute=30, hour=2),  # Daily at 2:30 AM
    },
    'cleanup-expired-token-blacklist': {
        'task': 'apps.auth_service.tasks.cleanup_expired_token_blacklist',
        'schedule': crontab(minute=0, hour=3),  # Daily at 3 AM
    },
    'security-audit-tokens': {
        'task': 'apps.auth_service.tasks.security_audit_tokens',
        'schedule': crontab(minute=0, hour='*/6'),  # Every 6 hours
    },
}

CELERY_TASK_ROUTES = {
    'auth_service.tasks.send_magic_link_email_async': {'queue': 'default'},
    'auth_service.tasks.send_email_verification_async': {'queue': 'default'},
    'auth_service.tasks.send_welcome_email_async': {'queue': 'default'},
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Add this for token blacklisting
    'corsheaders',  # If using CORS
    'django_celery_results',
    'django_celery_beat',

    # Local apps
    'auth_service.apps.AuthServiceConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    # Your CSRF exemption middleware MUST come before CsrfViewMiddleware
    # 'auth_service.middleware.api_csrf_middleware.CSRFExemptAPIMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # This should come AFTER your middleware
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'shared.middleware.security_middleware.SecurityMiddleware',
    'auth_service.middleware.jwt_blacklist_middleware.JWTBlacklistMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'receiptmanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'shared', 'templates'),
            os.path.join(BASE_DIR, 'email_templates'),  # Your pattern
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'receiptmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ReceiptManager',
        'USER': 'postgres',
        'PASSWORD': 'Riyaan$hM07',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'Receipt Manager <noreply@receiptmanager.com>'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "riyaanshmittal14@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Security Settings
MAX_FAILED_LOGIN_ATTEMPTS = 5
ACCOUNT_LOCK_MINUTES = 30
MAGIC_LINK_EXPIRY_MINUTES = 60
MAX_REQUESTS_PER_IP_PER_MINUTE = 60
MAX_AUTH_REQUESTS_PER_IP_PER_MINUTE = 10


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins (for development)

CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_HEADERS = [
#     "content-type",
#     "authorization",
#     "X-CSRFTOKEN",
#     "X-Requested-With",
# ]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] [%(levelname)s] [%(name)s] [corr_id=%(correlation_id)s] %(message)s",
        },
    },
    "filters": {
        "correlation": {
            "()": "shared.logging.CorrelationIdFilter",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["correlation"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
