# Generated by Django 5.2.6 on 2025-10-04 08:03

import django.core.validators
import django.db.models.deletion
import receipt_service.models.receipt
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("icon", models.CharField(help_text="Emoji icon", max_length=10)),
                ("color", models.CharField(help_text="Hex color code", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "receipt_categories",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="receipt_cat_slug_7279df_idx"),
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="receipt_cat_is_acti_aad9a3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FileField(
                        max_length=500,
                        upload_to=receipt_service.models.receipt.receipt_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(max_length=50)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash for duplicate detection",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("queued", "Queued for Processing"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Processing Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "processing_stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ocr", "OCR Extraction"),
                            ("parsing", "Data Parsing"),
                            ("categorization", "AI Categorization"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("processing_attempts", models.PositiveIntegerField(default=0)),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "ocr_confidence_score",
                    models.FloatField(
                        blank=True, help_text="OCR confidence 0.0-1.0", null=True
                    ),
                ),
                ("extracted_date", models.DateField(blank=True, null=True)),
                ("extracted_vendor", models.CharField(blank=True, max_length=255)),
                (
                    "extracted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("extracted_currency", models.CharField(default="USD", max_length=3)),
                (
                    "extracted_items",
                    models.JSONField(
                        blank=True, default=list, help_text="List of line items"
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI categorization confidence 0.0-1.0",
                        null=True,
                    ),
                ),
                (
                    "ai_reasoning",
                    models.TextField(blank=True, help_text="AI decision explanation"),
                ),
                (
                    "upload_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "suggested_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_receipts",
                        to="receipt_service.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "receipts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Transaction/receipt date")),
                ("vendor", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final confirmed amount",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="User-defined tags"
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        blank=True, help_text="Original AI confidence score", null=True
                    ),
                ),
                (
                    "user_corrected_amount",
                    models.BooleanField(
                        default=False, help_text="User modified extracted amount"
                    ),
                ),
                (
                    "user_corrected_category",
                    models.BooleanField(
                        default=False, help_text="User changed AI suggested category"
                    ),
                ),
                (
                    "user_corrected_vendor",
                    models.BooleanField(
                        default=False, help_text="User modified extracted vendor"
                    ),
                ),
                (
                    "user_corrected_date",
                    models.BooleanField(
                        default=False, help_text="User modified extracted date"
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("is_business_expense", models.BooleanField(default=False)),
                ("is_reimbursable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="receipt_service.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entry",
                        to="receipt_service.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Entry",
                "verbose_name_plural": "Ledger Entries",
                "db_table": "receipt_ledger_entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCategoryPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receipt_service.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "receipt_user_category_preferences",
            },
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["user", "-created_at"], name="receipts_user_id_b4de90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["status", "created_at"], name="receipts_status_3c94c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["processing_stage", "-processing_started_at"],
                name="receipts_process_48e4fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["file_hash"], name="receipts_file_ha_2b143f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["suggested_category", "-ai_confidence_score"],
                name="receipts_suggest_98c18c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["user", "-date"], name="receipt_led_user_id_c310ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["category", "-date"], name="receipt_led_categor_4d5862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["date", "-created_at"], name="receipt_led_date_1a7646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["user", "category", "-date"],
                name="receipt_led_user_id_aff65d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["user", "-amount"], name="receipt_led_user_id_cf5805_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["is_business_expense", "-date"],
                name="receipt_led_is_busi_b67a5c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usercategorypreference",
            index=models.Index(
                fields=["user", "-usage_count"], name="receipt_use_user_id_ae5e07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercategorypreference",
            index=models.Index(
                fields=["user", "-last_used"], name="receipt_use_user_id_ddc69a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercategorypreference",
            unique_together={("user", "category")},
        ),
    ]
