# Generated by Django 5.2.6 on 2025-10-05 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="receipt",
            name="receipts_status_3c94c2_idx",
        ),
        migrations.RemoveIndex(
            model_name="receipt",
            name="receipts_process_48e4fe_idx",
        ),
        migrations.RemoveIndex(
            model_name="receipt",
            name="receipts_suggest_98c18c_idx",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="ai_confidence_score",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="ai_reasoning",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="extracted_amount",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="extracted_currency",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="extracted_date",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="extracted_items",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="extracted_text",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="extracted_vendor",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="ocr_confidence_score",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="processing_attempts",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="processing_error",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="processing_stage",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="suggested_category",
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["status"], name="receipts_status_7da223_idx"),
        ),
    ]
