# Generated by Django 5.2.6 on 2025-10-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_service", "0002_remove_receipt_receipts_status_3c94c2_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledgerentry",
            name="ai_confidence_score",
        ),
    ]
